# Generated by Django 3.0.7 on 2020-06-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awardee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('last_name', models.CharField(max_length=50)),
                ('award', models.CharField(max_length=5)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('presentation_date', models.DateField()),
                ('recommender_first_name', models.CharField(max_length=50)),
                ('recommender_middle_initial', models.CharField(blank=True, max_length=1)),
                ('recommender_last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
