# Generated by Django 3.0.7 on 2020-06-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardee',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='awardee',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
